services:
  - type: web
    plan: free
    name: MeshRename
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/lavakumar2025/Mesh-RenameBot.git
    branch: master
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN
        sync: false
